name: Build on macOS arm64

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-15, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dev tools
        run: |
          bash check_prerequisites.sh
          bash link.sh
          # Add ASDF_HASHICORP_SKIP_VERIFY=1 because it somehow fails verifying checksums and signatures
          # Add MISE_RUBY_BUILD_OPTS=--disable-shared because SIP is disabled on GHA macOS runner
          ASDF_HASHICORP_SKIP_VERIFY=1 MISE_RUBY_BUILD_OPTS=--disable-shared bash install.sh
        shell: zsh {0}
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELL: /usr/bin/zsh
      - name: Source .zshrc
        run: source .zshrc
        shell: zsh {0}
        env:
          SHELL: /usr/bin/zsh
