name: Build environment on Ubuntu x86-64

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            autoconf \
            build-essential \
            libbz2-dev \
            libdb-dev \
            libffi-dev \
            libgdbm6 \
            libgdbm-dev \
            libgit2-dev \
            libgmp-dev \
            liblzma-dev \
            libncurses5-dev \
            libreadline6-dev \
            libsqlite3-dev \
            libssl-dev \
            libxml2-dev \
            libxmlsec1-dev \
            libyaml-dev \
            make \
            patch \
            rustc \
            tk-dev \
            unzip \
            uuid-dev \
            vim \
            xz-utils \
            zip \
            zlib1g-dev \
            zsh
          sudo apt-get clean && \
          sudo rm -rf /var/lib/apt/lists/*
      - name: Install dev tools
        run: |
          source .zshrc
          bash install.sh
        shell: zsh {0}
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELL: /usr/bin/zsh
