name: Build on Ubuntu x86_64

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install zsh
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends zsh
      - name: Install dev tools
        run: |
          bash check_prerequisites.sh
          bash install.sh
        shell: zsh {0}
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELL: /usr/bin/zsh
      - name: Source .zshrc
        run: source .zshrc
        shell: zsh {0}
        env:
          SHELL: /usr/bin/zsh
