[tools]
go = "latest"
lua = "latest"
node = "latest"
poetry = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
terraform = "1.3.1"
terragrunt = "0.52.2"
uv = "latest"
"npm:corepack" = "latest"

[settings]
experimental = true
