[tasks."update:mise"]
description = "Update mise and plugins"
run = "mise self-update --yes && mise upgrade --yes"

[tasks."update:brew"]
description = "Update Homebrew packages"
run = "brew update && brew upgrade && brew cleanup"

[tasks."update:aube"]
description = "Update aube global packages"
run = "aube update --latest --global"

[tasks.update]
description = "Run updates of all the dev tools"
depends = ["update:*"]

[tasks."doctor:mise"]
description = "Check mise installation for possible problems"
run = "source ~/.zprofile && mise doctor"

[tasks."doctor:brew"]
description = "Check possible problems with brew"
run = "brew doctor"

[tasks."doctor:aube"]
description = "Checks for known common issues with aube configuration"
run = "aube doctor"

[tasks.doctor]
description = "Check issues with configuration of all the dev tools"
depends = ["doctor:*"]

[tools]
actionlint = "latest"
aube = "latest"
aws-sso = "latest"
bat = "latest"
bottom = "latest"
claude = "latest"
ecspresso = "latest"
eza = "latest"
fd = "latest"
ghtkn = "latest"
git-cliff = "latest"
github-cli = "latest"
go = "latest"
go-jsonnet = "latest"
hadolint = "latest"
herdr = "latest"
lefthook = "latest"
lua = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "24"
"npm:@colbymchenry/codegraph" = "latest"
pinact = "latest"
pipx = "latest"
poetry = "latest"
python = { version = "3.11.17", postinstall = 'chmod -R g-w "$MISE_TOOL_INSTALL_PATH"' }
ripgrep = "latest"
ruby = "3.4.11"
rust = "latest"
sops = "latest"
starship = "latest"
stylua = "latest"
taplo = "latest"
terraform = "1.3.1"
terraform-ls = "latest"
terragrunt = "0.52.2"
tirith = "latest"
typos = "latest"
usage = "latest"
uv = "latest"
yarn = "4.13.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[settings.github]
credential_command = '"$HOME/.local/share/mise/installs/ghtkn/latest/ghtkn" get -m 1h'
