[tools]
actionlint = "latest"
aws-sso = "latest"
ecspresso = "latest"
github-cli = "latest"
go = "latest"
hadolint = "latest"
lua = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "20.12.2"
poetry = "latest"
python = "3.11.9"
ripgrep = "latest"
ruby = "3.1.5"
rust = "latest"
sops = "latest"
stylua = "latest"
taplo = "latest"
terraform = "1.3.1"
terraform-ls = "latest"
terragrunt = "0.52.2"
typos = "latest"
usage = "latest"
uv = "latest"
"npm:corepack" = "latest"

[settings]
experimental = true
